[general]
import = ["~/.config/alacritty/themes/gruber_darker.toml"]

[font]
normal.family = "FiraCode Nerd Font"
size = 15.0
offset = { y = 2 }

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[window.padding]
x = 10
y = 10

