[general]
import = ["~/.config/alacritty/themes/gruber_darker.toml"]

[font]
normal.family = "FiraCode"
size = 15.0
offset = { y = 2 }

[font.bold]
family = "FiraCode"
style = "Bold"

[font.italic]
family = "FiraCode"
style = "Italic"

