# Catppuccin Mocha Theme

[colors.primary]
background = "#1e1e2e"
foreground = "#e0def4"
cursor     = "#f5c2e7"

[colors.normal]
black   = "#1e1e2e"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#ff79c6"
cyan    = "#74c7ec"
white   = "#e0def4"

[colors.bright]
black   = "#6c7086"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#ff79c6"
cyan    = "#74c7ec"
white   = "#ffffff"

