#Gruber Darker Theme

[colors.primary]
background = "#181818"
foreground = "#e4e4ef"

[colors.cursor]
cursor = "#f4f4ff"

[colors.selection]
text = "#181818"
background = "#f4f4ff"

[colors.normal]
black   = "#101010"
red     = "#c73c3f"
green   = "#73c936"
yellow  = "#ffdd33"
blue    = "#96a6c8"
magenta = "#9e95c7"
cyan    = "#95a99f"
white   = "#f5f5f5"

[colors.bright]
black   = "#aaaaaa"
red     = "#ff4f58"
green   = "#73c936"
yellow  = "#ffdd33"
blue    = "#96a6c8"
magenta = "#9e95c7"
cyan    = "#ffffff"
white   = "#f4f4ff"

