# Tokyonight Dark Theme

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"
cursor     = "#f7768e"

[colors.normal]
black   = "#1a1b26"
red     = "#ff7a93"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#c0caf5"
white   = "#ffffff"

[colors.bright]
black   = "#3b4261"
red     = "#ff7a93"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#c0caf5"
white   = "#ffffff"

